language: cpp

git:
  submodules: false

services:
  - docker

before_install:
  - docker pull vgmtrans/vgmtrans-deps:tests_env
  - docker run -itd --name build vgmtrans/vgmtrans-deps:tests_env
  - docker exec build git clone --single-branch --branch refactor https://github.com/sykhro/vgmtrans /repo

script:
  - docker exec build cmake -DENABLE_UI_QT=OFF -H/repo -B/build
  - docker exec build cmake --build /build --target tests
