language: cpp

git:
  submodules: false

if: tag IS blank

language: cpp
compiler: gcc
sudo: require
dist: xenial

matrix:
  include:
    - os: linux
      before_install:
        - sudo add-apt-repository ppa:janisozaur/cmake-update -y
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo add-apt-repository ppa:beineri/opt-qt-5.11.1-xenial -y
        - sudo apt-get update -qq
        - sudo apt-get -y install g++-8 qt511base libfluidsynth-dev libgl1-mesa-dev cmake ninja-build        
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
        - source /opt/qt*/bin/qt*-env.sh
    - os: osx
      osx_image: xcode10.2
      before_install:
        - brew upgrade gcc || brew install gcc
        - brew upgrade cmake || brew install cmake
        - brew upgrade ninja || brew install ninja
        - brew upgrade fluid-synth || brew install fluid-synth
        # This image contains Qt5.12, and we're fine with that for now
        #- brew upgrade qt || brew install qt

script:
  - cmake --version
  - if [ ! -z $TRAVIS_BRANCH ] && [ "$TRAVIS_BRANCH" != "master" ] ; then
      export UPLOADTOOL_SUFFIX=$TRAVIS_BRANCH;
    fi
  - mkdir build && cd build
  - if [ $TRAVIS_OS_NAME = linux ]; then
      cmake -DCMAKE_BUILD_TYPE=Release  -DENABLE_TESTING=0 -DCMAKE_INSTALL_PREFIX=/usr/bin -GNinja .. ;
      ninja -j$(nproc) ;
      DESTDIR=appdir ninja -j$(nproc) install ; find appdir/ ;
      wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" ;
      chmod a+x linuxdeployqt-continuous-x86_64.AppImage ;
      mkdir -p appdir/usr/share ;
      cp ../data/vgmtrans.desktop appdir/usr/share ;
      cp ../data/mame_roms.xml appdir/usr/bin ;
      cp ../src/vgmtrans-qt/resources/images/logo.png appdir/usr/share/default.png ;
      ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/vgmtrans.desktop -appimage ;
    fi
  - if [ $TRAVIS_OS_NAME = osx ]; then
      CC=gcc-9 CXX=g++-9 cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTING=0 -GNinja .. ;
      ninja -j$(sysctl -n hw.physicalcpu) ;
      cp ../data/mame_roms.xml src/vgmtrans-qt/VGMTrans.app/Contents/MacOS/ ;
      /usr/local/opt/qt5/bin/macdeployqt src/vgmtrans-qt/VGMTrans.app -dmg -always-overwrite ;
      cd src/vgmtrans-qt/ ;
      zip -vr ../../VGMTrans-$(git rev-parse --short HEAD)-x86_64-osx.zip VGMTrans.app -x "*.DS_Store" ;
      mv VGMTrans.dmg ../../VGMTrans-$(git rev-parse --short HEAD)-x86_64-osx.dmg ;
      cd ../.. ;
    fi

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - if [ $TRAVIS_OS_NAME = linux ]; then
      bash upload.sh VGMTrans*.AppImage ;
    fi
  - if [ $TRAVIS_OS_NAME = osx ]; then
      bash upload.sh VGMTrans*.dmg ;
      bash upload.sh VGMTrans*.zip ;
    fi
