name: Build and test
on: [push, pull_request]
jobs:
  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'refactor'
      - name: "Install dependencies"
        run: |
          brew upgrade gcc@9 || brew install gcc@9
          brew upgrade ninja || brew install ninja
          brew upgrade cmake || brew install cmake
          brew upgrade qt || brew install qt
          brew upgrade fluid-synth || brew install fluid-synth
          echo ::set-env name=CXX::g++-9
          echo ::set-env name=CC::gcc-9
          echo "::set-env name=BRANCH::$(git rev-parse --abbrev-ref HEAD)"
          echo ::add-path::/usr/local/bin
      - name: "Prepare build"
        run: |
          mkdir build
          cd build
          cmake --version
          # Silly hack: by purging these variable we force cmake to use the CXX/CC variables
          cmake -DCMAKE_C_COMPILER="" -DCMAKE_CXX_COMPILER="" -DCMAKE_INSTALL_PREFIX=/usr/bin -DCMAKE_BUILD_TYPE=Release -G Ninja ..
      - name: "Build project"
        run: cmake --build build --config "Release" --parallel
      - name: "Run tests"
        run: ctest -C Release
      - working-directory: "build"
        name: "Package DMG (macOS)"
        run: |
          cp ../data/mame_roms.xml src/vgmtrans-qt/VGMTrans.app/Contents/MacOS/
          /usr/local/opt/qt5/bin/macdeployqt src/vgmtrans-qt/VGMTrans.app -dmg -always-overwrite
          cd src/vgmtrans-qt/
          mv VGMTrans.dmg ../..
      - name: "Upload artifact"
        uses: actions/upload-artifact@v1
        with:
          name: VGMTrans-${{ github.sha }}-${{ env.BRANCH }}-x86_64-${{ runner.os }}.dmg
          path: "build/VGMTrans.dmg"
  ubuntu:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'refactor'
      - name: "Install dependencies"
        run: |
          sudo add-apt-repository ppa:beineri/opt-qt-5.14.2-xenial -y
          sudo apt-get update -qq
          sudo apt-get -y install qt514base qt514wayland libjack-dev libsndfile1 libpulse-dev libglib2.0-dev ninja-build libgl1-mesa-dev
          wget https://github.com/FluidSynth/fluidsynth/archive/v2.1.2.zip
          unzip v2.1.2.zip
          cd fluidsynth-2.1.2
          mkdir build && cd build
          cmake -Denable-network=off -Denable-ipv6=off -DCMAKE_INSTALL_PREFIX=/usr/ -DLIB_INSTALL_DIR=lib -GNinja ..
          ninja make
          ninja install
          cd ../..
      - name: "Set environment variables"
        run: |
          echo ::set-env name=CXX::g++-9
          echo ::set-env name=CC::gcc-9
          echo "::set-env name=BRANCH::$(git rev-parse --abbrev-ref HEAD)"
      - name: "Prepare build"
        run: |
          mkdir build
          cd build
          cmake --version
          # Silly hack: by purging these variable we force cmake to use the CXX/CC variables
          cmake -DCMAKE_C_COMPILER="" -DCMAKE_CXX_COMPILER="" -DCMAKE_INSTALL_PREFIX=/usr/bin -DCMAKE_BUILD_TYPE=Release -GNinja ..
      - name: "Build project"
        run: cmake --build build --config "Release" --parallel
      - name: "Run tests"
        run: ctest -C Release
      - name: "Make AppImage"
        working-directory: "build"
        run: |
          DESTDIR=appdir ninja -j$(nproc) install
          find appdir/
          wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          chmod a+x linuxdeployqt-continuous-x86_64.AppImage
          mkdir -p appdir/usr/share
          cp ../data/vgmtrans.desktop appdir/usr/share
          cp ../data/mame_roms.xml appdir/usr/bin
          cp ../src/vgmtrans-qt/resources/images/logo.png appdir/usr/share/default.png
          ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/vgmtrans.desktop -appimage -qmake=/opt/qt514/bin/qmake -extra-plugins=platforms/ -verbose=2
          mv VGMTrans*.AppImage VGMTrans.AppImage
      - name: "Upload artifact"
        uses: actions/upload-artifact@v1
        with:
          name: VGMTrans-${{ github.sha }}-${{ env.BRANCH }}-x86_64-${{ runner.os }}.AppImage
          path: "build/VGMTrans.AppImage"
  windows:
    runs-on: windows-latest
    name: Windows
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'refactor'
      - name: "Install dependencies"
        run: |
          git submodule update --init --recursive
          Write-Output "::set-env name=CXX::cl"
          Write-Output "::set-env name=CC::cl"
          Write-Output "::set-env name=BRANCH::$(git rev-parse --abbrev-ref HEAD)"
      - name: "Prepare build"
        run: |
          mkdir build
          cd build
          cmake --version
          cmake -DCMAKE_BUILD_TYPE=Release ..
      - name: "Build project"
        run: cmake --build build --config "Release" --parallel
      - name: "Run tests"
        run: ctest -C Release
      - name: "Package artifact"
        working-directory: build
        run: |
          mkdir deploy
          copy src\vgmtrans-qt\Release\vgmtrans.exe deploy\vgmtrans.exe
          copy ..\data\mame_roms.xml deploy\
          copy ..\externals\win-deps\fluidsynth2-msvc2019-x64\*.dll deploy\
          # Someday windeployqt --release --no-translations --no-angle --no-opengl-sw deploy\vgmtrans.exe
          copy ..\externals\win-deps\qt5-msvc2019-x64\bin\Qt5Core.dll deploy\
          copy ..\externals\win-deps\qt5-msvc2019-x64\bin\Qt5Gui.dll deploy\
          copy ..\externals\win-deps\qt5-msvc2019-x64\bin\Qt5Widgets.dll deploy\
          mkdir deploy\qtdata
          xcopy ..\externals\win-deps\qt5-msvc2019-x64\plugins deploy\qtdata /s /e /h
          Set-Content -Value "[Paths]`nPlugins = ./qtdata" -Path deploy\qt.conf
          7z a "VGMTrans.zip" .\deploy\*
      - name: "Upload artifact"
        uses: actions/upload-artifact@v1
        with:
          name: VGMTrans-${{ github.sha }}-${{ env.BRANCH }}-x86_64-${{ runner.os }}
          path: "build/VGMTrans.zip"
